# Generated by Django 2.2.5 on 2021-07-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oekaki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
